{% set name = "bttoxin_digger" %}
{% set version = "1.0.1" %}

package:
  name: '{{ name }}'
  version: '{{ version }}'

source:
  url: https://github.com/liaochenlanruo/BtToxin_Digger/archive/v{{ version }}.tar.gz
  sha256: 

build:
  number: 0
  noarch: generic

requirements:
  host:
    - perl
    - perl-bioperl >=1.7.2
    - perl-file-tee

  run:
    - blast
    - hmmer
    - libsvm
    - perl-pod-usage
    - perl-getopt-long
    - perl-file-tee
    - pgcgap >=1.0.14

test:
  commands:
    - bttoxin_digger --version

about:
  home: https://github.com/liaochenlanruo/BtToxin_Digger/blob/master/README.md
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: A toxin minging tool for Bacillus thuringiensis
  dev_url: https://github.com/liaochenlanruo/BtToxin_Digger/tree/master

extra:
  identifiers:
    - biotools:bttoxin_digger
  recipe-maintainers:
    - liaochenlanruo
